Add multiple broker support to republisher
jamescarr/amqp-republisher pull request #4
Opened 2018-12-12 23:59 UTC by zrochler

This adds support for republishing across multiple brokers.

2018-12-17 09:31 UTC, kishorenc requested changes
There is typo that needs to be fixed. Can you also please test this PR by running it against 2 local instances of Rabbit?

2018-12-17 09:31 UTC, kishorenc commented on republish.py
> +    parser.add_argument('--paralellism', help='The max number of brokers to consume from in parallel', default=5, dest='parallelism')
@zrochler There is a typo here - it should be `parallelism`.

2018-12-17 23:21 UTC, zrochler commented
@kishorenc, I fixed the typo and tested against local instances, which needed one thing fixed.

2018-12-18 09:11 UTC, kishorenc approved these changes

2018-12-18 18:39 UTC, merged